"""Presentation-ready internal SmartPay portfolio and campaign dashboard."""

from __future__ import annotations


def render_admin_dashboard() -> str:
    return _PAGE


_PAGE = """<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light">
  <link rel="icon" href="/static/logos/mastercard.svg" type="image/svg+xml">
  <title>SmartPay Admin</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap');
    :root{--ink:#151923;--muted:#687081;--line:#e6e8ed;--soft:#f5f6f8;--red:#eb001b;--orange:#ff5f00;--yellow:#f79e1b;--green:#16876b;--blue:#3168d8;--shadow:0 16px 40px rgba(26,28,38,.08)}
    *{box-sizing:border-box}body{margin:0;background:#f4f5f7;color:var(--ink);font-family:'DM Sans',sans-serif;letter-spacing:0}button,input,select{font:inherit}button{cursor:pointer}.app{min-height:100vh}.topbar{height:74px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between;padding:0 34px;position:sticky;top:0;z-index:20}.brand{display:flex;align-items:center;gap:13px;font:800 21px 'Manrope'}.brand-mark{width:38px;height:30px;position:relative}.brand-mark:before,.brand-mark:after{content:'';position:absolute;top:2px;width:27px;height:27px;border-radius:50%}.brand-mark:before{left:0;background:var(--red)}.brand-mark:after{right:0;background:var(--yellow)}.brand-mark i{position:absolute;z-index:2;left:14px;top:2px;width:10px;height:27px;background:var(--orange);clip-path:polygon(35% 0,100% 0,65% 100%,0 100%)}.admin-label{font:600 12px 'Manrope';color:#fff;background:#1d2330;padding:5px 9px;border-radius:4px;margin-left:3px}.top-actions{display:flex;align-items:center;gap:18px;color:var(--muted);font-size:13px}.live{display:flex;align-items:center;gap:8px}.live i{width:8px;height:8px;border-radius:50%;background:#18a474;box-shadow:0 0 0 4px #e1f7ef}.avatar{width:36px;height:36px;border-radius:50%;background:#202634;color:#fff;display:grid;place-items:center;font-weight:700}
    .nav{height:58px;background:#fff;border-bottom:1px solid var(--line);display:flex;align-items:center;padding:0 34px;gap:30px}.nav-button{align-self:stretch;border:0;background:none;color:var(--muted);font-weight:600;padding:0 2px;border-bottom:3px solid transparent}.nav-button.active{color:var(--ink);border-color:var(--orange)}.shell{max-width:1440px;margin:auto;padding:34px 36px 64px}.view{display:none}.view.active{display:block;animation:enter .3s ease both}@keyframes enter{from{opacity:0;transform:translateY(6px)}}
    .page-head{display:flex;align-items:flex-end;justify-content:space-between;margin-bottom:28px}.eyebrow{margin:0 0 8px;color:var(--orange);font-size:12px;font-weight:700;text-transform:uppercase}.page-head h1{font:800 36px/1.1 'Manrope';margin:0}.page-head p{margin:9px 0 0;color:var(--muted);font-size:15px}.date-control{border:1px solid var(--line);background:#fff;border-radius:7px;padding:10px 13px;font-weight:600;color:#404756}.metrics{display:grid;grid-template-columns:repeat(5,1fr);gap:14px;margin-bottom:22px}.metric{background:#fff;border:1px solid var(--line);border-radius:8px;padding:20px;min-width:0;box-shadow:0 2px 8px rgba(0,0,0,.02)}.metric-top{display:flex;justify-content:space-between;align-items:center;color:var(--muted);font-size:12px;min-height:31px}.metric-icon{width:30px;height:30px;border-radius:7px;background:#fff3ec;color:var(--orange);display:grid;place-items:center;font-weight:800}.metric strong{display:block;font:800 29px 'Manrope';margin:13px 0 5px}.delta{font-size:11px;color:var(--green);font-weight:700}.delta span{color:var(--muted);font-weight:400;margin-left:4px}
    .grid{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(330px,.8fr);gap:20px}.panel{background:#fff;border:1px solid var(--line);border-radius:8px;box-shadow:0 3px 12px rgba(0,0,0,.025);overflow:hidden}.panel-head{display:flex;align-items:center;justify-content:space-between;padding:21px 23px;border-bottom:1px solid var(--line)}.panel-head h2{font:700 19px 'Manrope';margin:0}.panel-head p{font-size:12px;color:var(--muted);margin:5px 0 0}.legend{display:flex;gap:14px;font-size:11px;color:var(--muted)}.legend span{display:flex;align-items:center;gap:5px}.legend i{width:8px;height:8px;border-radius:50%}.chart-wrap{height:350px;padding:18px 20px 12px;position:relative}.chart-wrap canvas{width:100%;height:100%}.platforms{padding:10px 22px 19px}.platform{display:grid;grid-template-columns:105px 1fr 62px;gap:12px;align-items:center;padding:11px 0}.platform-name{display:flex;align-items:center;gap:9px;font-weight:600;font-size:13px}.platform-logo{width:28px;height:28px;border-radius:7px;display:grid;place-items:center;color:#fff;font-weight:800;font-size:11px}.chatgpt{background:#111}.gemini{background:linear-gradient(135deg,#4285f4,#a142f4)}.grok{background:#050505}.copilot{background:#7356bf}.claude{background:#c96846}.platform-track{height:8px;border-radius:6px;background:#edf0f4;overflow:hidden}.platform-track i{display:block;height:100%;border-radius:6px;background:linear-gradient(90deg,var(--red),var(--orange),var(--yellow))}.platform-value{text-align:right;font:700 13px 'Manrope'}.funnel{padding:18px 22px 24px}.funnel-step{margin-bottom:13px}.funnel-copy{display:flex;justify-content:space-between;font-size:12px;margin-bottom:6px}.funnel-copy strong{font-family:'Manrope'}.funnel-bar{height:26px;background:#f0f2f5;border-radius:4px;overflow:hidden}.funnel-bar i{display:block;height:100%;background:linear-gradient(90deg,#252b38,#555f74);border-radius:4px}.funnel-step:nth-child(3) .funnel-bar i{background:linear-gradient(90deg,var(--red),var(--orange))}.funnel-step:nth-child(4) .funnel-bar i{background:linear-gradient(90deg,var(--orange),var(--yellow))}.insight{margin-top:18px;background:#fff7f2;border-left:3px solid var(--orange);padding:13px;font-size:12px;line-height:1.5}.lower-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:20px}.mini-chart{height:230px;padding:18px}.mini-chart canvas{width:100%;height:100%}
    .flipper-head{position:relative;overflow:hidden;background:#171b25;color:#fff;border-radius:9px;padding:28px 32px;margin-bottom:22px;display:flex;align-items:center;justify-content:space-between}.flipper-head h1{font:800 38px 'Manrope';margin:0}.flipper-head p{color:#bcc3d0;max-width:650px;margin:8px 0 0}.flipper-art{width:250px;height:110px;position:relative}.flip-card{position:absolute;width:126px;height:78px;border-radius:9px;box-shadow:0 12px 24px rgba(0,0,0,.25)}.flip-card.red{background:linear-gradient(135deg,#8e0011,var(--red));right:84px;top:20px;transform:rotate(-11deg)}.flip-card.orange{background:linear-gradient(135deg,var(--orange),var(--yellow));right:18px;top:8px;transform:rotate(10deg)}.flip-arrow{position:absolute;left:98px;top:36px;color:#fff;font-size:42px;font-weight:800;z-index:3;transform:rotate(-10deg)}
    .campaign-layout{display:grid;grid-template-columns:minmax(0,1.4fr) minmax(340px,.7fr);gap:20px}.builder{padding:0}.step{padding:24px 26px;border-bottom:1px solid var(--line)}.step:last-child{border:0}.step-title{display:flex;align-items:flex-start;gap:13px;margin-bottom:18px}.step-number{width:28px;height:28px;border-radius:50%;background:#fff0e8;color:var(--orange);display:grid;place-items:center;font-weight:800;font-size:12px;flex:none}.step-title h3{font:700 16px 'Manrope';margin:2px 0}.step-title p{margin:4px 0 0;color:var(--muted);font-size:12px}.field-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.field{display:grid;gap:7px}.field label{font-size:11px;font-weight:700;color:#4e5666}.field input,.field select{width:100%;border:1px solid #dcdfe5;border-radius:6px;padding:11px 12px;background:#fff;color:var(--ink);outline:none}.field input:focus,.field select:focus{border-color:var(--orange);box-shadow:0 0 0 3px rgba(255,95,0,.1)}.currency-wrap,.suffix-wrap{position:relative}.currency-wrap span,.suffix-wrap span{position:absolute;top:50%;transform:translateY(-50%);color:var(--muted);font-size:13px}.currency-wrap span{left:12px}.suffix-wrap span{right:12px}.currency-wrap input{padding-left:26px}.suffix-wrap input{padding-right:38px}.card-selector{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.card-option{position:relative}.card-option input{position:absolute;opacity:0}.card-option label{display:block;border:1px solid var(--line);border-radius:7px;padding:12px;cursor:pointer;min-height:72px}.card-option input:checked+label{border-color:var(--orange);background:#fff7f2;box-shadow:0 0 0 1px var(--orange)}.card-option strong,.card-option span{display:block}.card-option strong{font-size:12px}.card-option span{font-size:10px;color:var(--muted);margin-top:5px}.usage-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.usage{border:1px solid var(--line);border-radius:7px;padding:13px}.usage-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:12px}.usage-head strong{font-size:12px}.channel-symbol{font-size:17px;color:var(--orange)}.stepper{display:grid;grid-template-columns:30px 1fr 30px;gap:6px}.stepper button{border:1px solid var(--line);background:#f7f8fa;border-radius:5px;font-weight:700}.stepper input{text-align:center;border:1px solid var(--line);border-radius:5px;padding:7px 2px;width:100%}
    .campaign-preview{position:sticky;top:154px}.preview-card{background:#171b25;color:#fff;padding:24px;border-radius:8px 8px 0 0}.preview-label{color:#9da5b5;font-size:10px;text-transform:uppercase}.preview-card h2{font:800 23px 'Manrope';margin:8px 0}.offer{display:flex;align-items:baseline;gap:7px;margin:18px 0}.offer strong{font:800 45px 'Manrope';color:var(--yellow)}.offer span{font-size:14px;color:#d8dde6}.unlock{background:#252b38;border-radius:6px;padding:13px;font-size:12px;line-height:1.5}.preview-metrics{background:#fff;border:1px solid var(--line);border-top:0;border-radius:0 0 8px 8px;padding:18px}.preview-row{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid #eef0f3;font-size:12px}.preview-row:last-of-type{border:0}.preview-row strong{font-family:'Manrope'}.coverage{margin:15px 0}.coverage-copy{display:flex;justify-content:space-between;font-size:11px;margin-bottom:6px}.coverage-track{height:7px;background:#eceff3;border-radius:5px;overflow:hidden}.coverage-track i{display:block;height:100%;background:linear-gradient(90deg,var(--red),var(--orange),var(--yellow));width:72%}.launch{width:100%;border:0;border-radius:6px;padding:13px;background:var(--orange);color:#fff;font-weight:700;margin-top:8px}.launch:hover{background:#e85400}.saved{margin-top:18px}.saved h3{font:700 16px 'Manrope';margin:0 0 10px}.campaign-item{background:#fff;border:1px solid var(--line);border-radius:7px;padding:13px;margin-bottom:8px}.campaign-item-top{display:flex;justify-content:space-between;gap:10px}.campaign-item strong{font-size:12px}.campaign-item span{font-size:10px;color:var(--muted)}.campaign-item em{font-style:normal;color:var(--green);background:#eaf8f3;border-radius:99px;padding:3px 7px;font-size:9px}
    .toast{position:fixed;right:28px;bottom:28px;background:#171b25;color:#fff;border-radius:7px;padding:14px 18px;box-shadow:var(--shadow);font-size:13px;opacity:0;transform:translateY(10px);pointer-events:none;transition:.25s}.toast.show{opacity:1;transform:none}
    @media(max-width:1050px){.metrics{grid-template-columns:repeat(2,1fr)}.grid,.campaign-layout{grid-template-columns:1fr}.campaign-preview{position:static}.flipper-art{display:none}.card-selector{grid-template-columns:repeat(2,1fr)}}
    @media(max-width:620px){.topbar,.nav{padding-left:18px;padding-right:18px}.top-actions .live{display:none}.shell{padding:24px 18px 50px}.page-head{align-items:flex-start;gap:18px}.page-head h1,.flipper-head h1{font-size:29px}.date-control{display:none}.metrics{grid-template-columns:1fr 1fr}.metric{padding:15px}.metric strong{font-size:22px}.metric-top{font-size:10px}.grid,.lower-grid{grid-template-columns:1fr}.chart-wrap{height:275px}.panel-head{align-items:flex-start;gap:10px}.legend{display:none}.platform{grid-template-columns:90px 1fr 54px}.flipper-head{padding:24px 20px}.step{padding:20px}.field-grid,.usage-grid,.card-selector{grid-template-columns:1fr}.nav{gap:22px;overflow:auto}.nav-button{white-space:nowrap}.campaign-layout{display:block}.campaign-preview{margin-top:18px}}
  </style>
</head>
<body>
<div class="app">
  <header class="topbar"><div class="brand"><span class="brand-mark"><i></i></span>SmartPay <span class="admin-label">ADMIN</span></div><div class="top-actions"><span class="live"><i></i> Live portfolio data</span><span class="avatar">MC</span></div></header>
  <nav class="nav" aria-label="Admin sections"><button class="nav-button active" data-view="dashboard">Dashboard</button><button class="nav-button" data-view="campaigns">Campaigns</button></nav>
  <main class="shell">
    <section class="view active" id="dashboard">
      <div class="page-head"><div><p class="eyebrow">Mastercard internal</p><h1>Portfolio performance</h1><p>SmartPay adoption, engagement and conversion across the AI ecosystem.</p></div><select class="date-control" aria-label="Reporting period"><option>Last 12 months</option><option>Last 90 days</option><option>Year to date</option></select></div>
      <div class="metrics">
        <article class="metric"><div class="metric-top"><span>Installed users</span><i class="metric-icon">U</i></div><strong>12.8M</strong><div class="delta">+24.6% <span>year over year</span></div></article>
        <article class="metric"><div class="metric-top"><span>SmartPay interactions</span><i class="metric-icon">I</i></div><strong>186.4M</strong><div class="delta">+31.2% <span>year over year</span></div></article>
        <article class="metric"><div class="metric-top"><span>Bank accounts linked</span><i class="metric-icon">B</i></div><strong>8.7M</strong><div class="delta">+18.9% <span>68% of users</span></div></article>
        <article class="metric"><div class="metric-top"><span>Card switches</span><i class="metric-icon">S</i></div><strong>2.14M</strong><div class="delta">+42.1% <span>conversion events</span></div></article>
        <article class="metric"><div class="metric-top"><span>Funded offers used</span><i class="metric-icon">%</i></div><strong>3.62M</strong><div class="delta">+37.8% <span>redemptions</span></div></article>
      </div>
      <div class="grid">
        <article class="panel"><div class="panel-head"><div><h2>SmartPay growth</h2><p>Monthly active users and interactions, millions</p></div><div class="legend"><span><i style="background:#ff5f00"></i>Active users</span><span><i style="background:#252b38"></i>Interactions</span></div></div><div class="chart-wrap"><canvas id="growth-chart" aria-label="SmartPay growth over time"></canvas></div></article>
        <article class="panel"><div class="panel-head"><div><h2>Installs by AI platform</h2><p>Connected SmartPay users</p></div></div><div class="platforms"><div class="platform"><span class="platform-name"><i class="platform-logo chatgpt">C</i>ChatGPT</span><span class="platform-track"><i style="width:100%"></i></span><strong class="platform-value">5.4M</strong></div><div class="platform"><span class="platform-name"><i class="platform-logo gemini">G</i>Gemini</span><span class="platform-track"><i style="width:67%"></i></span><strong class="platform-value">3.6M</strong></div><div class="platform"><span class="platform-name"><i class="platform-logo grok">X</i>Grok</span><span class="platform-track"><i style="width:35%"></i></span><strong class="platform-value">1.9M</strong></div><div class="platform"><span class="platform-name"><i class="platform-logo copilot">M</i>Copilot</span><span class="platform-track"><i style="width:24%"></i></span><strong class="platform-value">1.3M</strong></div><div class="platform"><span class="platform-name"><i class="platform-logo claude">A</i>Claude</span><span class="platform-track"><i style="width:11%"></i></span><strong class="platform-value">0.6M</strong></div></div></article>
      </div>
      <div class="lower-grid"><article class="panel"><div class="panel-head"><div><h2>Value conversion</h2><p>From install to Mastercard-funded value</p></div></div><div class="funnel"><div class="funnel-step"><div class="funnel-copy"><span>App installed</span><strong>12.8M</strong></div><div class="funnel-bar"><i style="width:100%"></i></div></div><div class="funnel-step"><div class="funnel-copy"><span>Bank account linked</span><strong>8.7M</strong></div><div class="funnel-bar"><i style="width:68%"></i></div></div><div class="funnel-step"><div class="funnel-copy"><span>Switched payment behavior</span><strong>2.14M</strong></div><div class="funnel-bar"><i style="width:42%"></i></div></div><div class="funnel-step"><div class="funnel-copy"><span>Mastercard discount redeemed</span><strong>3.62M</strong></div><div class="funnel-bar"><i style="width:53%"></i></div></div><div class="insight"><strong>High-intent signal:</strong> linked users are 3.4x more likely to move spend to a recommended Mastercard.</div></div></article><article class="panel"><div class="panel-head"><div><h2>Switches and redemptions</h2><p>Monthly completed outcomes, thousands</p></div></div><div class="mini-chart"><canvas id="outcomes-chart" aria-label="Card switches and offer redemptions over time"></canvas></div></article></div>
    </section>

    <section class="view" id="campaigns">
      <div class="flipper-head"><div><p class="eyebrow">Mastercard growth engine</p><h1>Flipper</h1><p>Turn competitor-card spend into sustained Mastercard preference with precisely funded, behavior-unlocked incentives.</p></div><div class="flipper-art" aria-hidden="true"><span class="flip-card red"></span><span class="flip-arrow">&#8594;</span><span class="flip-card orange"></span></div></div>
      <div class="campaign-layout"><form class="panel builder" id="campaign-form">
        <div class="step"><div class="step-title"><span class="step-number">1</span><div><h3>Campaign and funding</h3><p>Name the initiative and set the Mastercard-funded pool.</p></div></div><div class="field-grid"><div class="field"><label for="campaign-name">Campaign name</label><input id="campaign-name" value="Everyday Spend Cashback" required></div><div class="field"><label for="campaign-budget">Funding amount</label><div class="currency-wrap"><span>$</span><input id="campaign-budget" type="number" min="100000" step="100000" value="25000000"></div></div></div></div>
        <div class="step"><div class="step-title"><span class="step-number">2</span><div><h3>Competitor card portfolio</h3><p>Select the cards whose active spend you want to flip.</p></div></div><div class="card-selector"><div class="card-option"><input type="checkbox" id="amex-gold" checked data-audience="1450000"><label for="amex-gold"><strong>Amex Gold</strong><span>1.45M eligible users</span></label></div><div class="card-option"><input type="checkbox" id="amex-platinum" data-audience="620000"><label for="amex-platinum"><strong>Amex Platinum</strong><span>620K eligible users</span></label></div><div class="card-option"><input type="checkbox" id="discover-it" checked data-audience="1180000"><label for="discover-it"><strong>Discover it</strong><span>1.18M eligible users</span></label></div><div class="card-option"><input type="checkbox" id="csp" data-audience="940000"><label for="csp"><strong>Chase Sapphire Preferred</strong><span>940K eligible users</span></label></div><div class="card-option"><input type="checkbox" id="cfu" checked data-audience="1720000"><label for="cfu"><strong>Chase Freedom Unlimited</strong><span>1.72M eligible users</span></label></div><div class="card-option"><input type="checkbox" id="capone" data-audience="810000"><label for="capone"><strong>Capital One Venture</strong><span>810K eligible users</span></label></div></div></div>
        <div class="step"><div class="step-title"><span class="step-number">3</span><div><h3>Spend and incentive criteria</h3><p>Define the spend threshold to unlock a flat, Mastercard-funded cash back reward -- never a percentage tied to any one purchase.</p></div></div><div class="field-grid"><div class="field"><label for="annual-spend">Minimum spend to unlock</label><div class="currency-wrap"><span>$</span><input id="annual-spend" type="number" min="500" step="250" value="3000"></div></div><div class="field"><label for="cashback">Cash back reward</label><div class="currency-wrap"><span>$</span><input id="cashback" type="number" min="50" step="50" value="500"></div></div></div></div>
        <div class="step"><div class="step-title"><span class="step-number">4</span><div><h3>Usage unlock</h3><p>The cash back unlocks once the cardholder reaches this many Mastercard purchases of any kind -- never one specific merchant -- within the unlock window.</p></div></div><div class="usage-grid"><div class="usage"><div class="usage-head"><strong>Purchases required</strong><span class="channel-symbol">#</span></div><div class="stepper"><button type="button" data-step="-1">-</button><input id="unlock-count" class="usage-count" aria-label="Mastercard purchases required" type="number" min="1" value="40"><button type="button" data-step="1">+</button></div></div><div class="usage"><div class="usage-head"><strong>Unlock window</strong><span class="channel-symbol">&#8987;</span></div><div class="stepper"><button type="button" data-step="-1">-</button><input id="unlock-window" class="usage-count" aria-label="Unlock window in days" type="number" min="1" value="90"><button type="button" data-step="1">+</button></div></div></div></div>
      </form><aside class="campaign-preview"><div class="preview-card"><span class="preview-label">Flipper campaign preview</span><h2 id="preview-name">Everyday Spend Cashback</h2><div class="offer"><strong id="preview-discount">$500</strong><span>Mastercard-funded cash back</span></div><div class="unlock" id="preview-unlock">Unlock after 40 Mastercard purchases totalling $3,000 within 90 days.</div></div><div class="preview-metrics"><div class="preview-row"><span>Eligible audience</span><strong id="preview-audience">4.35M</strong></div><div class="preview-row"><span>Spend to unlock</span><strong id="preview-spend">$3,000</strong></div><div class="preview-row"><span>Cash back per cardholder</span><strong id="preview-incentive">$500</strong></div><div class="preview-row"><span>Funded conversions</span><strong id="preview-conversions">20,833</strong></div><div class="coverage"><div class="coverage-copy"><span>Audience coverage</span><strong id="coverage-label">0.5%</strong></div><div class="coverage-track"><i id="coverage-bar"></i></div></div><button class="launch" type="submit" form="campaign-form">Create Flipper campaign</button></div><div class="saved"><h3>Live campaigns</h3><div id="campaign-list"><div class="campaign-item"><div class="campaign-item-top"><strong>Everyday Spend Cashback</strong><em>Live</em></div><span>$18M funded · 40 purchases / $3,000 to unlock · 61% claimed</span></div><div class="campaign-item"><div class="campaign-item-top"><strong>Travel Wallet Cashback</strong><em>Live</em></div><span>$12M funded · 12 purchases / $2,000 to unlock · 44% claimed</span></div></div></div></aside></div>
    </section>
  </main><div class="toast" id="toast">Campaign created and queued for approval.</div>
</div>
<script>
  const navButtons=[...document.querySelectorAll('.nav-button')];
  navButtons.forEach(button=>button.addEventListener('click',()=>{navButtons.forEach(item=>item.classList.toggle('active',item===button));document.querySelectorAll('.view').forEach(view=>view.classList.toggle('active',view.id===button.dataset.view));}));

  function drawLineChart(canvasId,series){const canvas=document.getElementById(canvasId);const ratio=devicePixelRatio||1;const rect=canvas.getBoundingClientRect();canvas.width=rect.width*ratio;canvas.height=rect.height*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);const w=rect.width,h=rect.height,p={l:42,r:16,t:16,b:30};ctx.clearRect(0,0,w,h);ctx.font='11px DM Sans';ctx.fillStyle='#858d9c';ctx.strokeStyle='#eceef2';ctx.lineWidth=1;for(let i=0;i<5;i++){const y=p.t+(h-p.t-p.b)*i/4;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();}const months=['Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep'];months.forEach((m,i)=>{if(i%2===0||w>700){const x=p.l+(w-p.l-p.r)*i/(months.length-1);ctx.fillText(m,x-9,h-8);}});const all=series.flatMap(s=>s.values);const min=Math.min(...all)*.86,max=Math.max(...all)*1.04;series.forEach(s=>{ctx.beginPath();s.values.forEach((v,i)=>{const x=p.l+(w-p.l-p.r)*i/(s.values.length-1);const y=p.t+(h-p.t-p.b)*(1-(v-min)/(max-min));i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.strokeStyle=s.color;ctx.lineWidth=3;ctx.lineJoin='round';ctx.stroke();s.values.forEach((v,i)=>{const x=p.l+(w-p.l-p.r)*i/(s.values.length-1);const y=p.t+(h-p.t-p.b)*(1-(v-min)/(max-min));ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fillStyle=s.color;ctx.fill();});});}
  const growth=[{color:'#ff5f00',values:[4.2,4.7,5.3,5.9,6.6,7.4,8.3,9.1,10.0,10.9,11.8,12.8]},{color:'#252b38',values:[5.1,5.7,6.2,6.9,7.6,8.4,9.2,10.1,10.8,11.5,12.2,13.1]}];
  const outcomes=[{color:'#eb001b',values:[108,119,131,145,151,166,174,188,196,207,219,232]},{color:'#f79e1b',values:[176,190,208,221,242,258,274,291,309,322,337,351]}];
  function drawCharts(){drawLineChart('growth-chart',growth);drawLineChart('outcomes-chart',outcomes)}drawCharts();addEventListener('resize',drawCharts);

  const form=document.getElementById('campaign-form');const budget=document.getElementById('campaign-budget');const spend=document.getElementById('annual-spend');const cashback=document.getElementById('cashback');
  function compact(value){return value>=1000000?(value/1000000).toFixed(2).replace(/0$/,'')+'M':value>=1000?Math.round(value/1000)+'K':String(value)}
  function updatePreview(){const selected=[...document.querySelectorAll('.card-option input:checked')];const audience=selected.reduce((sum,item)=>sum+Number(item.dataset.audience),0);const maxIncentive=Number(cashback.value);const conversions=maxIncentive?Math.floor(Number(budget.value)/maxIncentive):0;const unlockCount=Number(document.getElementById('unlock-count').value);const unlockWindow=Number(document.getElementById('unlock-window').value);document.getElementById('preview-name').textContent=document.getElementById('campaign-name').value||'Untitled Flipper';document.getElementById('preview-discount').textContent='$'+Number(cashback.value).toLocaleString();document.getElementById('preview-audience').textContent=compact(audience);document.getElementById('preview-spend').textContent='$'+Number(spend.value).toLocaleString();document.getElementById('preview-incentive').textContent='$'+maxIncentive.toLocaleString();document.getElementById('preview-conversions').textContent=conversions.toLocaleString();document.getElementById('preview-unlock').textContent=`Unlock after ${unlockCount} Mastercard purchases totalling $${Number(spend.value).toLocaleString()} within ${unlockWindow} days.`;const coverage=audience?Math.min(100,conversions/audience*100):0;document.getElementById('coverage-label').textContent=coverage.toFixed(1)+'%';document.getElementById('coverage-bar').style.width=coverage+'%';}
  form.addEventListener('input',updatePreview);document.querySelectorAll('[data-step]').forEach(button=>button.addEventListener('click',()=>{const input=button.parentElement.querySelector('input');input.value=Math.max(0,Number(input.value)+Number(button.dataset.step));updatePreview();}));
  form.addEventListener('submit',event=>{event.preventDefault();const item=document.createElement('div');item.className='campaign-item';item.innerHTML=`<div class="campaign-item-top"><strong>${document.getElementById('campaign-name').value}</strong><em>Draft</em></div><span>$${Number(budget.value).toLocaleString()} funded · awaiting approval</span>`;document.getElementById('campaign-list').prepend(item);const toast=document.getElementById('toast');toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2600);});updatePreview();
</script>
</body></html>"""